# Generated by Django 3.2.4 on 2021-07-09 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210709_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='highest_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.CharField(blank=True, default='', help_text='Enter the URL of an image, using 300 characters or less.', max_length=300),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Enter a category name using 100 characters or less.', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(help_text='Enter a comment using 500 characters or less.', max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='listing_category', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(help_text='Enter a description using 500 characters or less.', max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_title',
            field=models.CharField(help_text='Enter a title using 100 characters or less.', max_length=100),
        ),
    ]
