# Generated by Django 3.2.4 on 2021-07-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210709_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.CharField(help_text='Enter the URL of an image, using 300 characters or less.', max_length=300),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
